services:
  gpx-prediction:
    container_name: gpx-prediction
    build:
      dockerfile: Dockerfile
    volumes:
      - ./cloudflare-warp:/var/lib/cloudflare-warp
      - ./checkpoint:/app/checkpoint
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - TZ=Asia/Taipei
    tty: true
    stdin_open: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
